### ISSUE TITLE
Support Authentication

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#1]
It's JWT.
Already been done in Tiwun Awesome and Tiwun Mobile.

**Comment by Alir3z4** [comment]
All the pages should be login required as well as all the API endpoints are already protected to be working only with authenticated users.

**Comment by amirm3hdi** [comment]
@Alir3z4 Can you setup auth service and controller/templates by me?

**Comment by Alir3z4** [comment]
@amirm3hdi @ArsalanSavand if this is done, you can close it

**Comment by ArsalanSavand** [comment]
Already done... all pages and stuff needs Authentication.

**Comment by Alir3z4** [comment]
Awesome
