### ISSUE TITLE
Embed Github Gist 

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#1033]
GitHubGist: https://gist.github.com/Alir3z4/6038313
Embedding would be: `<script src="https://gist.github.com/Alir3z4/6038313.js"></script>`

Feature Request on Forum: https://forum.gonevis.com/d/45-embedding-github-gist

**Comment by Alir3z4** [comment]
This is now supported by the backend.

All the following text should produce the `<script src="https://gist.github.com/Alir3z4/6038313.js"></script>`:

* Pasting `<script src="https://gist.github.com/Alir3z4/6038313.js"></script>` directly into the editor.
* Pasting `https://gist.github.com/Alir3z4/6038313.js` directly into the editor.
* Pasting `https://gist.github.com/Alir3z4/6038313` into the editor.

**Comment by ArsalanSavand** [comment]
@Alir3z4 I have so many things on my hand today, but I will try to make this happen today.

**Comment by Alir3z4** [comment]
@ArsalanSavand this is how you should listen on the iframe:

```html
<script>
	window.addEventListener("message", receiveMessage);

	function receiveMessage(event) {
	  if (event.origin === "http://gonevis.local:8000") { // Always check the origin to be GoNevis domain (based on the environment of course)
	    gistIframe = document.getElementById(event.data.elementId);
		gistIframe.setAttribute("height", event.data.height);
	  }
	}
</script>



<iframe id="https://gist.github.com/Alir3z4/3557d3a78932992d705f0580647c74a4" width="100%" frameborder="0" allowfullscreen src="http://gonevis.local:8000/toodartoo/gist-github/?gist_url=https://gist.github.com/Alir3z4/3557d3a78932992d705f0580647c74a4"></iframe>
```

Notice the `iframe.id` is the gist_url as well.
