### ISSUE TITLE
Issue with pre-formatted in posts

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#1035]
1. If you draft a post and place a pre-formatted text `</>` in the post, fill it with some code, then save the draft or publish it - you are unable to add text before or after the `</>` block if you edit the post again.  Only if you place the block between existing lines of other texts, will it be possible to edit outside the `</>` block.
2. The `</>` block still is mangled in published post. 
3. Still no syntax highlights for the `</>` block.

**Comment by ArsalanSavand** [comment]
@Alir3z4 Highlighting works exactly the same in both frontend and backend.
User should be able to see what he/she wrote. Otherwise every time user changed highlighting theme at settings page, he/she should go and see it in the blog (which is annoying).

@Alir3z4 What do you think?

**Comment by Alir3z4** [comment]
So both frontend and backend at the same time use the same highlight theme, ok.
Thanks for confirming.

**Comment by AmirSavand** [comment]
No, I said we don't need it initially to release such feature in templates along with dash.

They are separated.

**Comment by LarsFosdal** [comment]
@ArsalanSavand - ref. point 2: 

Besides the lack of syntax highlighting options (such as selecting the language) - in this very simple example, the leading white space is missing in the rendered post view.

Edit view: 
https://drive.google.com/open?id=1jQsrCCucmEaqS_Ycokwm6A2aDfZxlxuM

Post view
https://drive.google.com/open?id=1GDTzae6mgJJbfBqDUv35L0L83_6ZQWoI

**Comment by LarsFosdal** [comment]
> 3. I have not added highlighting to the editor, because @AmirSavand thinks we don't need highlighting in frontend. My opinion is that user should see his/her current theme and more.

If I post snippets in Delphi, C#, SQL, JSON, PowerShell, HTML/CSS, Go, Java - how do I get the appropriate highlighting for each syntax?
Is it the idea to only have a generic <pre> block without highlighting, and instead use embedded gists or PasteBin entries if you want full highlighting?

Example right here in GitHub using markdown/code fencing and indicating language:
```delphi
program first;
begin
  Writeln('Hello First!');
end.
```

**Comment by ArsalanSavand** [comment]
@LarsFosdal Reply to your comment: https://github.com/SavandBros/gonevis-dash/issues/1035#issuecomment-445711540

I saw the screenshots you shared and I will fix it quickly.

**Comment by ArsalanSavand** [comment]
@LarsFosdal Reply to your comment: https://github.com/SavandBros/gonevis-dash/issues/1035#issuecomment-445712815

I will try to set a tooltip or a helper on editor's buttons.

**Comment by ArsalanSavand** [comment]
@LarsFosdal Reply to your question: https://github.com/SavandBros/gonevis-dash/issues/1035#issuecomment-445711540

All the languages and all the codes have only one highlighting syntax which you can choose your desire highlighting syntax from blog settings page ( this feature is not published yet ).

**Comment by Alir3z4** [comment]
@ArsalanSavand what's the conclusion of this ?

**Comment by ArsalanSavand** [comment]
@Alir3z4 All the requests on this issue has been resolved, only thing left is adding tooltip (helper) to editor buttons.
