### ISSUE TITLE
Some themes do not honor the </> tags.

### ISSUE THREAD

**Issue by LarsFosdal** [SavandBros/gonevis-dash#1038]
FYI - It seems that most of the themes also more or less ignore the formatting of </> blocks, and condense/unwrap the text, i.e. remove line breaks and doesn't use a fixed width font)  - making those themes unusable for people that post </> snippets:

Some photo oriented themes appropriately strip the </> blocks from the stream.

**Comment by AmirSavand** [comment]
Please provide screenshot of the issue.

**Comment by LarsFosdal** [comment]
F.x. from the "Beta" theme.  As you can see, there is a </> block at the
end which is partially included.  This happens with several themes.  Also -
"Beta" seems to have other issues related to lack of whitespace.

**Comment by ArsalanSavand** [comment]
@Alir3z4 I think this issue should be close, all themes are now fixed.
