### ISSUE TITLE
Show subscribed blogs in reader

### ISSUE THREAD

**Issue by AmirSavand** [SavandBros/gonevis-dash#1051]
So there should be somewhere to see how many subscribed blogs I got, can be a modal or a page dedicated to it. It should all be as a child of reader view.

When showing the blogs, unsubscribed button should be next to them. I think it also needs a pagination.

@Alir3z4 you got anything else in mind?

**Comment by Alir3z4** [comment]
I like the idea for sure.
It makes sense to have list of blogs that I have subscribed.

@AmirSavand can you do a quick screen design of what you have in mind so we can shape the API to get the data for it ?

**Comment by AmirSavand** [comment]
Already discussed it with @ArsalanSavand, it's basically a button/link in the feed view that you click and view the list of blogs you're following.
