### ISSUE TITLE
Import of Google+ posts

### ISSUE THREAD

**Issue by LarsFosdal** [SavandBros/gonevis-dash#1057]
Google+ is closing before April 2019.

There is an export tool that can export posts from a G+ users feed, pages and communities into three different formats.
https://blog.friendsplus.me/export-google-plus-feeds-45926c925891

- An open JSON format documented here
https://docs.google.com/document/d/1gOYJe61sI1GbO9qpFZJtwY3vdsZalsxtPgUnB2cvzAw/
- Blogger Backup format (XML)
- Wordpress eXtended RSS file (WXR / XML)

It would be great if GoNevis could import one or more of these formats!

**Comment by AmirSavand** [comment]
@Alir3z4 does back-end support it?
