### ISSUE TITLE
Set the correct JWT expiration date in Cookies

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#1085]
I just checked the JWT in the cookies.
The expiration date is set in 1969 in the cookies which is wrong.

![image](https://user-images.githubusercontent.com/591113/50576452-25a93080-0e23-11e9-8d0b-047e36619b3a.png)

The expiration date is included in JWT itself.

Get exp date from the JWT token and set the cookies expiration date based on that.

**Comment by AmirSavand** [comment]
It's ok to set it to never, once the token is denied by backend, front-end automatically logs out with a message.

**Comment by ArsalanSavand** [comment]
I'm on it.
