### ISSUE TITLE
Remove "Title" input in editor.

### ISSUE THREAD

**Issue by ArsalanSavand** [SavandBros/gonevis-dash#1086]
Remove "Title" input in editor and instead get the first written line and use it as post/page 's title.

**Comment by Alir3z4** [comment]
Keep in mind, `title` max length is `255`, anything more than that should be forced to new line.

**Comment by Alir3z4** [comment]
This issue is pinned now.
Good luck <3

**Comment by AmirSavand** [comment]
What's wrong with the current title input? It's cleaner and less confusing!

**Comment by ArsalanSavand** [comment]
@Alir3z4 what should we do with this issue?
