### ISSUE TITLE
Migrating blogs from WordPress to GoNevis.com

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#1094]
### The Process of Migrating from Dashboard

* User will find the Import tab in the Blog settings page.
* Select on WordPress and upload the `WordPress eXtended RSS file.`.
* Once importing is done, the blog owner will be notified about the result.
  * If success, the email notification contains the number of imported posts and tags.
  * If failure, we simply let the user know something has happened and we're looking into it.

Upon success of the backend, let the user know they will be notified via email when it's done.

Message: `Importing your blog is in progress, you will be notified by email when it's done.`

### How to upload the XML file.

Upload the XML file via Dolphin endpoints, just the way it's done when uploading images etc, but don't show the Dolphin file modal etc, just upload it directly.

### Endpoint 

The endpoint to call is `/api/v1/website/site/<pk>/import-blog/` and required data are:

```json
{"file_id": "<DOLPHIN_UPLOADED_FILE.ID>", "platform": "<ExportFilePlatform.WORD_PRESS>"}
```

The platforms are defined as:

```python
class ExportFilePlatform:
    WORD_PRESS = 0
    BLOGGER = 1
```

Feature Request on the forum: https://forum.gonevis.com/d/59-migration-blogs-from-wordpress-to-gonevis-com/2

**Comment by ArsalanSavand** [comment]
I'm on it...

**Comment by Alir3z4** [comment]
The issue is not longer blocked.
Also please don't mention the Blogger, only WordPress is supported for now.

**Comment by AmirSavand** [comment]
@ArsalanSavand destroy this.
