### ISSUE TITLE
Embedding imgur.com

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#1101]
I like imgur

Sample post https://imgur.com/gallery/q2CKBaz
```
<blockquote class="imgur-embed-pub" lang="en" data-id="q2CKBaz"><a href="//imgur.com/q2CKBaz">Slightly delayed reaction time.</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>
```

We have 2 options:

* Using GoNevis iframes as proxy
* Simply writing that into the post data.

Which one should we go with @ArsalanSavand ?

**Comment by ArsalanSavand** [comment]
@Alir3z4 I think we should go with our GoNevis iframe.
The main reason is that if I want to use it's `blockcode` I would have repetitive codes.
If we GoNevis iframe as proxy I would change small amount of codes.

@Alir3z4 what do you think?

**Comment by Alir3z4** [comment]
I agree, the iframe is a better option!
Put this feature on hold until we have the backend ready for it.
