### ISSUE TITLE
Fix sidebar doesn't get disappeared specially when navigating to 'write' route.

### ISSUE THREAD

**Issue by ArsalanSavand** [SavandBros/gonevis-dash#1128]
This bug was reported by @AmirSavand .

**Comment by AmirSavand** [comment]
I will try not to switch from staging to prod and use dash.

See if I can reproduce this again, if so, you need to make a whole new way of dealing with transmission of that page.

**Comment by ArsalanSavand** [comment]
This issue only occurs when switching from 'dev' environment to 'prod'.

**Comment by ArsalanSavand** [comment]
@AmirSavand Do you still observe this issue?
