### ISSUE TITLE
Google AdService Conversion 

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#1158]
First step, change the google analytics code to:

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-58251754-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-58251754-3');
  gtag('config', 'AW-830696480');
</script>
```

Finally, use the below details for "Signup" Conversion;

To do this, whenever someone a new user signups during creating a blog make such thing simply make the following call.

```
gtag('event', 'conversion', {
      'send_to': 'AW-830696480/6qhhCL6HnJEBEKDYjYwD',
      'event_callback': callback
  });
```

However, I'm not sure what `callback` should be.
Google suggest this:

![image](https://user-images.githubusercontent.com/591113/55682123-9175ca80-5937-11e9-9eef-23fd2d5f0f77.png)

**Comment by Alir3z4** [comment]
Setting this to blocked until I figure out some more info about the setup.

**Comment by Alir3z4** [comment]
First step, change the google analytics code to:

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-58251754-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-58251754-3');
</script>

```

**Comment by AmirSavand** [comment]
🍻 Let's do this.

**Comment by Alir3z4** [comment]
Please replace with this new one `AW-761190808/050HCLzP_qoBEJiz--oC
