### ISSUE TITLE
Move post status tabs next to search bar to save space

### ISSUE THREAD

**Issue by AmirSavand** [SavandBros/gonevis-dash#1162]
![image](https://user-images.githubusercontent.com/4629328/55683186-a8231e00-5945-11e9-8d93-ef6350a6174b.png)

For better UI/UX turn the status tabs into dropdown and move them next to the search bar so we'd also have less wasted space.

@Alir3z4 do you agree?

**Comment by Alir3z4** [comment]
Umm, not really.

It will turn into more confusion. The draft and published are main status of the content and it's far to give them separate visible tab for them.

I would say to save space, it would make sense to merge status bar (_the one with select and action button_) with the Page tabs (_Draft and Published_). That probably would save a lot of space.

**Comment by AmirSavand** [comment]
Ok will just move it next to search input and keep it as tabs/buttons.
