### ISSUE TITLE
Entry Entry Editor

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#12]
Which editor should be picked?

* ckEditor
* Medium Editor
* http://textangular.com/

**Comment by ArsalanSavand** [comment]
I think this is what we need !!

https://github.com/showdownjs/showdown

**Comment by Alir3z4** [comment]
http://www.dreamincode.net/forums/topic/246337-a-simple-text-editor-in-html-javascript-and-a-tiny-bit-of-css/

**Comment by Alir3z4** [comment]
I might even start my own.

**Comment by ArsalanSavand** [comment]
Done!
