### ISSUE TITLE
Lookup tags by Slug and not ID

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#228]

**Comment by ArsalanSavand** [comment]
@Alir3z4 What do you mean? and which part of Gonevis dash?

**Comment by Alir3z4** [comment]
@ArsalanSavand 

* Tags List
* Tag Details

Any other place of the code should remain untouched, only that 2 parts.

**Comment by amirm3hdi** [comment]
@ArsalanSavand Meaning when you are `get`ing the tags, you should use their `slug` not `id`.

**Comment by ArsalanSavand** [comment]
This issue has been solved. Long time ago.
