### ISSUE TITLE
Cannot Add cover image to Tag

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#233]
Whenever I try to add a cover image to a tag, it fails.
I see the console shows "PUT action is not allowed."

I've checked and backend for this, it works as expected.
After looking at the frontend, I see it's passing a `tag_site` param to tag endpoint, which I guess it's the cause of the issue.

**Comment by ArsalanSavand** [comment]
@Alir3z4 Issue is now Fixed.
