### ISSUE TITLE
Ordering tags based on how many times they've been used

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#242]
Ordering field: tagged_items_count

**Comment by amirm3hdi** [comment]
We will add it in a later version.

**Comment by Alir3z4** [comment]
Then don't close it, leave it open and just remove the milestone ;)

**Comment by amirm3hdi** [comment]
Ok, but it'll be open for a long time.

**Comment by AmirSavand** [comment]
@ArsalanSavand check if it can be done or not.
@Alir3z4 is this ready to be implemented?

**Comment by Alir3z4** [comment]
Yes, Ordering field is called `tagged_items_count`

**Comment by AmirSavand** [comment]
@ArsalanSavand then you can finish it.

**Comment by Alir3z4** [comment]
Ok, the backend had a bug and wasn't able to pick this up.
I'll make it work and remove the unblock tag from the issue here.

**Comment by AmirSavand** [comment]
This issue was born the same time as GoNevis. I think it's time to close this.

**Comment by Alir3z4** [comment]
This is fixed from backend and you can use it on frontend.
However, at this moment the orders are based on `tagged_items_count` by default.
Meaning tags with higher items will be first by default.

@ArsalanSavand if you intend to implement reverse ordering (`-tagged_items_count`) you can continue doing so otherwise close the issue
