### ISSUE TITLE
Editor font is not suitable for writing

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#251]
Plus it hurts my eyes as well.
Have a look at the screenshot:

![screenshot-dash draft gonevis com 2016-12-25 23-07-01](https://cloud.githubusercontent.com/assets/591113/21472500/02766d10-caf7-11e6-8563-8dd1cd13e6f4.png)

This is an screenshot from medium editor:

![screenshot-medium com 2016-12-25 23-08-51](https://cloud.githubusercontent.com/assets/591113/21472503/21909c16-caf7-11e6-8022-920b2d999a8a.png)

**Comment by amirm3hdi** [comment]
The font and styles were applied when you copied the text.
