### ISSUE TITLE
Minimal and cleaner "mass action" on Entries list

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#276]
:rage1: :rage2: :rage3: :rage4: This is rage :rage1: :rage2: :rage3: :rage4: 
![screenshot_20170101_002803](https://cloud.githubusercontent.com/assets/591113/21579152/66b3ab14-cfb9-11e6-92cd-27e43bf54979.png)

Below items can become "Swipe or Slide" widget.

* Disable Comment & Enable Comment 
* Draft & Published
* Set to Featured & Remove from Featured

**Comment by AmirSavand** [comment]
This is already updated and the actions look smooth.
