### ISSUE TITLE
Fix local storage on update user profile  

### ISSUE THREAD

**Issue by ArsalanSavand** [SavandBros/gonevis-dash#28]
We need to update local storage with the current view, when user is trying to update his profile 

@amirm3hdi fix it !

**Comment by Alir3z4** [comment]
You can use $broadcast and $on to get this done.

**Comment by ArsalanSavand** [comment]
@Alir3z4 no I've already fixed it, but the new code that @amirm3hdi just replaced with mine, made it a new issue here...

**Comment by ArsalanSavand** [comment]
@Alir3z4 
He will fix it soon, he just forgot to make a single call at Auth service!

**Comment by Alir3z4** [comment]
Alright. Sounds good

**Comment by Alir3z4** [comment]
Is this done, if so close please
