### ISSUE TITLE
Tag image (auto-complete) is ugly

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#384]
The screenshot below speaks for itself.

![screenshot_20170319_223126](https://cloud.githubusercontent.com/assets/591113/24083624/d7c4ddc4-0cf3-11e7-8fdf-44ad197b1454.png)

**Comment by amirm3hdi** [comment]
@Alir3z4 this is already fixed but not on prod yet.

**Comment by Alir3z4** [comment]
Why it hasn't been pushed to prod yet?
The bug exists on the production.
Please deploy the fix to production if it's good by you.
