### ISSUE TITLE
Filter image selection for images only via backend

### ISSUE THREAD

**Issue by AmirSavand** [SavandBros/gonevis-dash#399]
Currently it is done by front-end.

**Comment by ArsalanSavand** [comment]
Requires backend.

**Comment by AmirSavand** [comment]
Created the backend issue.

**Comment by Alir3z4** [comment]
Made the required backend changes.
You can use File endpoint described as follow:

New filter called `ext`.

* `/dolphin/file/?ext=audio`
* `/dolphin/file/?ext=audio&ext=image` (*Can handle multiple ext at the same time*)

Allowed extensions:
  * image
  * audio
  * video
  * doc
  * archive

**Comment by AmirSavand** [comment]
@ArsalanSavand you know what to do.
