### ISSUE TITLE
Ability to show password

### ISSUE THREAD

**Issue by Momjo** [SavandBros/gonevis-dash#415]

**Comment by Alir3z4** [comment]
This is good, @AmirSavand it would make sense to the password in view mode as well, so user will see the password entered.

Both for Login and Register.

**Comment by AmirSavand** [comment]
Ok

**Comment by AmirSavand** [comment]
@Alir3z4 I think it should be for reset password and signup only.

**Comment by Alir3z4** [comment]
@AmirSavand and login.
It's useful, this is nice https://login.mailchimp.com

lots of password are being randomly generated and no one knows what they're typing anymore.
