### ISSUE TITLE
Advanced files view and download

### ISSUE THREAD

**Issue by AmirSavand** [SavandBros/gonevis-dash#442]

**Comment by Alir3z4** [comment]
@AmirSavand do you want to add more details to this to make it more clear and why do you think it would be something good ?

**Comment by AmirSavand** [comment]
I'll do some improvement and make it easier to browse and manage files.

**Comment by Alir3z4** [comment]
Nice!
What do you have in mind ?

**Comment by AmirSavand** [comment]
> I'll do some improvement and make it easier to browse and manage files.

**Comment by Alir3z4** [comment]
Ok, let's see what you gonna bring.
Can't wait to see them
