### ISSUE TITLE
Feedback should be contact form

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#455]
On some browser `mailto:` can be disabled to set to no action.
or simply user may not have email client configured for such link.

The best way around this would be opening a tiny contact form so user can submit from there.
It should have 2 required input fields. Subject and Message.

However, the backend doesn't provide any endpoint for this feature, so I set this blocked until the backend supports this. Once it's available I'll update it.

Ready to be implemented => https://github.com/SavandBros/gonevis-dash/issues/455#issuecomment-411526504

**Comment by AmirSavand** [comment]
@Alir3z4 Do we have an option for happy or sad face?
Like the VS Code feedback.

**Comment by Alir3z4** [comment]
What would be the benefit of that ?
I haven't used or noticed it, how it works and how we can get the most out of it ?

**Comment by AmirSavand** [comment]
I don't know, we can separate positive and negative feedback.

**Comment by Alir3z4** [comment]
"I don't know is not enough".

Although I agree with categorizing negative and positive feedbacks but I
don't want to have extra options around feedback flow.

The feedback process should be fairly simple and minimal.

User is putting time on providing feedbacks. We don't want them to go
through extra clicks.

**Comment by AmirSavand** [comment]
ok

**Comment by Alir3z4** [comment]
To add extra reasons, consider our simple `mailto` feedback link.
It simply opens up a compose email page/form withing the user OS default email client, user would enter subject and message, **that's it**.

Categorization might help us to easily manage the feedbacks, but it won't be nice or necessary on end user side.

**Comment by AmirSavand** [comment]
@Alir3z4 does this have an endpoint or just a mailto?

**Comment by AmirSavand** [comment]
Unblocked since it's front-end mailto only.

**Comment by Alir3z4** [comment]
I want to make an endpoint of it and collect user feedbacks in that way.
What information do you think we should let use enter.

In my opinion, we should only show a text box and let use enter a message in it.
Would that be good ? or you like a "Satisfied/Like" and "Dissatisfied/Dislike" face/icon as well ?

**Comment by AmirSavand** [comment]
A 1-out-of-5 rating with a tell-us-why input is good.

**Comment by AmirSavand** [comment]
Blocked since we need backend.

**Comment by Alir3z4** [comment]
What if user is going to just ask a question ?
Would star rating makes sense at all ?

**Comment by AmirSavand** [comment]
Isn't it feedback? ok rating can be optional.

**Comment by Alir3z4** [comment]
Yes, rating can be optional as well.
The message is very important here, the rating can be optional and if they
like to enter.

Alright, I'll make a task for this on the backend and take care of it

**Comment by AmirSavand** [comment]
@Alir3z4 if this is not ready in backend, we should do this next release then.

**Comment by Alir3z4** [comment]
That's OK.
Will have it in another release then.

**Comment by Alir3z4** [comment]
This is not blocked anymore.

The API endpoint: `POST:/api/zero/feedback/`  => `{message: "This is really nice!"}`

Once the message has been sent, show a message saying:

> We received your feedback, thank you <3

And then close the feedback widget.
