### ISSUE TITLE
Switch to files tab after files uploaded

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#508]
Having the modal open after the upload has been finished is confusing.
Once the file has been uploaded it should be inserted into text area where the cursor is.

Have a look at the below image;

![image](https://user-images.githubusercontent.com/591113/27270743-78bbc966-54d1-11e7-9022-2ba1174cf798.png)

I have finished upload the image but nothing has been inserted into the text editor.

**Comment by AmirSavand** [comment]
@Alir3z4 we can change tab to files once they are uploaded, but should not close modal, user could upload mutifile and maybe just forgot to upload some other file.

So main task: Switch to files tab after uploads finish.
