### ISSUE TITLE
Have the change Picture/Avatar on the Avatar itself in Account Settings

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#511]
The `avatar` button doesn't look where it is right now.

![image](https://user-images.githubusercontent.com/591113/27271454-e67e9a6a-54d5-11e7-9ede-89ccc65ce750.png)

Move the action on the picture place holder as well.
It should say:

Upload a picture: When there's no picture.
Change you profile photo: When there's an picture already in place.

**Comment by ArsalanSavand** [comment]
I don't understand, the avatar button placeholder should say that?
