### ISSUE TITLE
When email not verified: Disable Publishing an Entry

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#531]
An Entry can be created and have fun and kept in Draft, however in cannot be "Published".
Disable the "Published" radio button and "Update" button underneath it with message saying "Please verify your email first."

The same should apply on Entry list so user won't be able to set the set the status of an entry to published.

**Comment by AmirSavand** [comment]
@Alir3z4 we display the message:
![image](https://user-images.githubusercontent.com/4629328/28492098-9a324632-6f0d-11e7-8f63-70d5bdd517da.png)

But I will make a modal and ask user to verify.

**Comment by Alir3z4** [comment]
Да хорошо

On Sat, Jul 22, 2017 at 6:43 PM, Amir Mehdi Savand <notifications@github.com
