### ISSUE TITLE
Hover effect on Comment/Entries

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#541]
When I hover on their rows, nothing happens:

![image](https://user-images.githubusercontent.com/591113/27532187-73dc9584-5a70-11e7-8e34-c1a5ce56e194.png)

and 

![image](https://user-images.githubusercontent.com/591113/27532244-a65545d8-5a70-11e7-9976-5bcbb9ed7a3f.png)

It would be nice if there was a tiny hover effect on them, like a small shadow or anything, something that lets me the pointer is on them.

**Comment by ArsalanSavand** [comment]
I'm on it
