### ISSUE TITLE
Remove Grid-View for Entry list

### ISSUE THREAD

**Issue by ArsalanSavand** [SavandBros/gonevis-dash#572]
### Bugs

We have to remove Grid-View for Entry list. There are so many reasons why should we do this:

 - In Grid-View entry titles are so small and can't be fit in entry cards.
 - It prevents from ability to Select all entries.
 - Unnecessary view.

Entry title is the most important thing that should be fully displayed. No entry title has 3 words.

###  Features

If we remove this we can have the ability to have " Select All Entries " ability

**Comment by AmirSavand** [comment]
This is not a blocker.

**Comment by AmirSavand** [comment]
No, I disagree, many like me, want to see only entry cover, or they have an Instagram-like blog, so if it is even bad, you can just switch.
