### ISSUE TITLE
Update rollbar to latest version

### ISSUE THREAD

**Issue by AmirSavand** [SavandBros/gonevis-dash#584]

**Comment by AmirSavand** [comment]
@Alir3z4 make a form out of `ng-rollbar` and give me the URL of it.

**Comment by Alir3z4** [comment]
@AmirSavand on the readme it says:

> Since version 1.7.2 the version of ng-rollbar equals the official rollbar.js version. So if you install 1.8.0 of this library you will get rollbar.js in version 1.8.0.

**Comment by AmirSavand** [comment]
@Alir3z4 update me ASAP.

**Comment by Alir3z4** [comment]
We don't need this anymore
