### ISSUE TITLE
Open sidebar on entry submission

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#653]
currently it just says ""Error, Entry couldn't be updated. Try again" which doean't say anything about the actual error while the error has been returned from API.

If the error is 400 then the error should be reported to user so it can be fixed.

**Comment by AmirSavand** [comment]
@Alir3z4 It does show the error under the input that has the error.
It even shows the general/non field errors too.

**Comment by Alir3z4** [comment]
Can you check and show me how it works with an screenshot ?
It seems to me that if the error happens to a field in the sidebar and sidebar is not opened, the user will not see the sidebar. right ?

**Comment by AmirSavand** [comment]
If user submits the entry the sidebar is open.
Unless he presses enter in entry title.

**Comment by Alir3z4** [comment]
So the sidebar won't open then.
@AmirSavand we need to open the sidebar if the error happens to be in the sidebar

**Comment by AmirSavand** [comment]
ok

**Comment by Alir3z4** [comment]
Awesome <3

**Comment by ArsalanSavand** [comment]
@Alir3z4 I can't do it, I will reassign this issue to @AmirSavand
