### ISSUE TITLE
Long file name breaks out of modal header

### ISSUE THREAD

**Issue by Momjo** [SavandBros/gonevis-dash#676]
**Wrap text is not working with underscore sign between the word:**

![imagefilename](https://user-images.githubusercontent.com/19407713/29074616-49a928de-7c50-11e7-8ed8-be20d7027a4d.png)

![imagefilename1](https://user-images.githubusercontent.com/19407713/29074715-96fdbbcc-7c50-11e7-8ef7-d685f5d4554c.png)

**Comment by AmirSavand** [comment]
@Momjo this is an easy one, just use `break-word` https://developer.mozilla.org/en-US/docs/Web/CSS/word-break

**Comment by ArsalanSavand** [comment]
This issue is already fixed.

![image](https://user-images.githubusercontent.com/15196063/29078672-1aeb86d8-7c6c-11e7-95a0-3dc6e47abf6a.png)

**Comment by Momjo** [comment]
that does not work if you use underscore between words, like that **Devil_my_cry_4_Devil**

**Comment by AmirSavand** [comment]
@ArsalanSavand: @Momjo is right, if the words are together without any spaces it'll break out.

**Comment by ArsalanSavand** [comment]
@Momjo  OK I got it, I will fix it now
