### ISSUE TITLE
Upgrade CircleCI to use version 2

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#714]

**Comment by AmirSavand** [comment]
https://circleci.com/docs/2.0/migrating-from-1-2/

**Comment by AmirSavand** [comment]
@Alir3z4 what do you think? Should we upgrade or not?

**Comment by Alir3z4** [comment]
It's a pain to be honest, nothing to gain from this.
I'm closing.

**Comment by Alir3z4** [comment]
Back to this.
We're going to use WebPack and the build process is much much easier in this.

Once https://github.com/SavandBros/gonevis-dash/pull/871 is merged, I'll be working on this.

**Comment by AmirSavand** [comment]
@Alir3z4 change the milestone seems like it's not resolved yet.

**Comment by Alir3z4** [comment]
I've changed the milestone already and will be working on this soon.
