### ISSUE TITLE
Posts per page

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#725]
Each site can have setting for showing how many posts it wants to show on each page.
The setting key is on Site Settings update `paginate_by`.

* The label of field: **Number of posts show at most**
* Min: 1
* Max: 24

**Comment by AmirSavand** [comment]
Very good.

**Comment by Alir3z4** [comment]
At this time, themes don't support manipulating website settings, this is a site wide settings that user will be changing it. Later we can implement that theme feature.

Please make a feature request in the backend.
