### ISSUE TITLE
Tour for Entries doesn't look right

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#726]
Have a look at the picture below:

![image](https://user-images.githubusercontent.com/591113/29998855-4bc9ca56-9046-11e7-9c94-fc6a93732852.png)

**Comment by AmirSavand** [comment]
@ArsalanSavand This is pretty simple, after loading comments and entries, you call a function.

That function will check to see if both are loaded then shows the tour.
