### ISSUE TITLE
Let the Tour have "Skip" and "Next" buttons

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#727]
This is confusing

![image](https://user-images.githubusercontent.com/591113/29998866-d40f5692-9046-11e7-8e23-5a2962ec3d5e.png)

**Comment by Alir3z4** [comment]
Very importantianto

**Comment by AmirSavand** [comment]
@Alir3z4 did anyone complain about this? Do we still need this? (note: tour is only for main (dash) view)

**Comment by Alir3z4** [comment]
No one has.
However, usually if you provide a tip or a tour, it would be appropriate to skip it as well.
Some people like me, prefer to discover not being told to how.

You can see the same behavior on other application or desktop app when they give you a "getting started" or "startup tips" and you can "close", "see later" or even "don't show again" button.

Simply have a Skip button to skip the whole tour.
