### ISSUE TITLE
Medium text editor

### ISSUE THREAD

**Issue by AmirSavand** [SavandBros/gonevis-dash#737]

**Comment by Alir3z4** [comment]
Before getting anything in the master, becareful with all of their implementation.
Some of its plugins don't work with AngularJS and you might have to write some custom code to get them working.

**Comment by AmirSavand** [comment]
Yes.

**Comment by Alir3z4** [comment]
[](http://ct.fra.bz/ol/fz/sw/i37/2/9/20/frabz-sir-yes-sir-3d0bcd.jpg)
