### ISSUE TITLE
Site Setting: Search Engine Visibility

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#739]
There's a setting on Site that states "search_engine_visibility", by default it's `True` for all the websites.
Include this feature in the settings page of the website.

* Backend field on Site: `search_engine_visibility`
* The label of field: **Let search engine discover my site**
* Default: True/Checked

**Comment by AmirSavand** [comment]
@Alir3z4 does this come with the site setting? because the pagination didn't and it's blocked.

**Comment by Alir3z4** [comment]
It does come with it.
The other one does too
