### ISSUE TITLE
Commenting section re-design

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#749]
The "comments:" section is basically useless.
To me it seems to be en extra page.

We cannot do much in it.
It's confusing to work with.
I don't know how to open the and see the actual comment.

I'm thinking about a more minimal design and cleaner way of handling comments page.
It might be better to remove the page and embed the comments in the "Posts" page as well.

@AmirSavand and @ArsalanSavand  what do you think we should do about it ?

**Comment by AmirSavand** [comment]
Where user can see all comments if we remove it?

**Comment by AmirSavand** [comment]
Where user can see all comments if we remove it?

**Comment by Alir3z4** [comment]
I think embedding the comments under posts on posts page would be a good idea.

**Comment by AmirSavand** [comment]
Yes, but it's necessary to see ALL comments (latest for example) together.

**Comment by Alir3z4** [comment]
> Yes, but it's necessary to see ALL comments (latest for example) together.

Indeed, so embedding won't do much, However having embedding would be really helpful to easily see the comments of each post.

Now, back to the original issue.
How can be enhance the comments page to be more useful and helpful for the users.
What do you see in it that you can think could be enhanced ?

**Comment by AmirSavand** [comment]
Check these out:

![image](https://user-images.githubusercontent.com/4629328/30512351-7f57fcc2-9afe-11e7-9f4c-aa0fe2eb3bdd.png)

![image](https://user-images.githubusercontent.com/4629328/30512359-9884fb8c-9afe-11e7-94df-05600dccaf0f.png)


We could add multi select to do actions and or ability to show comments by posts (like a filter or search).

**Comment by Alir3z4** [comment]
Multi-select is a good idea and seems to be missing feature right now.
How would you do filtering then ?

We can't show a search box and expect user to search for a post to filter them based on the selected post.

That's where embedding comments in the post list view comes handy. each post would have its comments embedded below of its card.
