### ISSUE TITLE
Set cover image from the images in the content

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#766]
So when user editing the posts and inserts an image, if there's no cover image on the posts, set that image to be the cover image.

Reported by https://twitter.com/ricardoMillardo

**Comment by bizreack** [comment]
Thanks for adding the suggestion. I would really love the functionality.

**Comment by Alir3z4** [comment]
@bizreack The features is now live on production.
We also have changed the Cover Image button functionality as well.

Let us know if you find anything weird with it.
