### ISSUE TITLE
How is the app with mobile browser ?

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#811]
I've received some complains regarding the app not being much of compatible with the mobile browser.
Please test with mobile and see how the whole flow works.

As long as we don't have the mobile application we need to make it up with the browser app.

**Comment by AmirSavand** [comment]
Any certain issues? like what page?

**Comment by Alir3z4** [comment]
Some complained about the editor
Also file uploaders seems to behaving not easy on mobile.

You might be able to spot them by using it via mobile (ios or android.)

**Comment by Alir3z4** [comment]
@AmirSavand I used my phone to go through it
It's no something that can be useful to be honest.

**Comment by AmirSavand** [comment]
No dashboard is easy on mobile (web).

We can make a minimal version for mobile and/or disable some features on mobile browser.

But we can fix as much as possible.

**Comment by AmirSavand** [comment]
For this, we can fix design issues, but we can't make it a 100% working mobile app.

**Comment by Alir3z4** [comment]
I don't think we need to make it 100% mobile friendly.
It's too much to have in a mobile, however since we don't want to do 100%
mobile crazy it would be better to have a mobile app to just let user know
to install it.

What do you think ?

**Comment by AmirSavand** [comment]
We don't have a mobile app.

**Comment by Alir3z4** [comment]
An option.
We have many users coming from mobile.

Since we don't have a mobile app, we better to have our app mobile friendly.

**Comment by Alir3z4** [comment]
Currently menus, dashboard, modals and especially editor is very hard to use in a mobile browser.

**Comment by AmirSavand** [comment]
@ArsalanSavand create a new css for mobile improvements. I'll help you.

**Comment by Alir3z4** [comment]
As previously discussed, one of them user has reported that it's not possible to upload/insert image when using the Editor via mobile browser.

@ArsalanSavand where are we with that ?

**Comment by ArsalanSavand** [comment]
@Alir3z4 the upload/insert has been fixed, since I'm working on mobile app I think we should remove some of our dashboard pages on small screens ( navigations and etc. ) .

I will later on fix navbar on small screens.
