### ISSUE TITLE
Create page entries

### ISSUE THREAD

**Issue by AmirSavand** [SavandBros/gonevis-dash#818]

**Comment by Alir3z4** [comment]
What's this exactly ?
any description ?

**Comment by AmirSavand** [comment]
@Alir3z4 creating pages, for now it's impossible, no options for it.

We need to add an option to editor for page instead of posts.

**Comment by AmirSavand** [comment]
Will update description later.

**Comment by Alir3z4** [comment]
I see.
Since we have removed the the "pages" from "posts" page, once this feature is implemented we can deploy.
