### ISSUE TITLE
Domain error message 

### ISSUE THREAD

**Issue by Momjo** [SavandBros/gonevis-dash#820]
Remove error message when you canceled to add domain.

![screenshot-dash gonevis com-2018 02 19-12-00-41](https://user-images.githubusercontent.com/19407713/36423753-60070840-1641-11e8-8ece-d6f4d768c820.png)

**Comment by AmirSavand** [comment]
@ArsalanSavand get on it.

**Comment by Alir3z4** [comment]
Thanks for reporting, good catch.
