### ISSUE TITLE
Using CkEditor

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#836]
Let's get CKEditor into the dash and use it as the editor.

**Comment by Alir3z4** [comment]
OK, all the available integrations are working with version 4.
We can make a new integration for version 5 but right now we can put that on hold until we get more stuff done.

I'll set this issue as blocked now.

**Comment by AmirSavand** [comment]
We have a label for that.

**Comment by AmirSavand** [comment]
What's the final decision here? What editor(s) are we going to be using?

**Comment by Alir3z4** [comment]
Since we have the Lazy Loading feature we can include this giant editor
with no problem.
Its resources will be loaded only when user navigate to the editor view.

If we can find the latest version of the editor it will be great, although
the v4 version is still in use in many places already but I don't like to
get in stuck with an old version of it..
We need to get our hands on the latest version of the ckeditor and
integrate.

However, I searched the internet and so far there's no ready made
integration yet and looking at the interface of both ck4 and ck5, we can
have a completely similar interface in ck4 as well.
You can have a look at https://ckeditor.com/ckeditor-4/#article and see it.

For angular integration, there's https://github.com/lemonde/angular-ckeditor
already but Im sure we have to fork it and update bunch of stuff based on
the new pull request is has. The project has not been updated since 2016.

**Comment by AmirSavand** [comment]
I agree.

What about current editor (Medium)? Can't we do something about it so we can fix it's bugs?

**Comment by Alir3z4** [comment]
The current one has tons to be fixed and always has a weird behavior.
Changing lines, changing formatting suddenly.

What we need a a blogging platform, is a real solid editor that we can trust and build upon and not something that might change the behavior unexpectedly.

If there's a feature in the editor, it should work as expected. The current one always gives me weird behavior, different stuff happen and one thing that happens all the time is changing the formatting of the text when I make a new line etc.

Again, sure we can spent time and fix its issues, but why not spent that time on other issues while having a "battle-tested" editor take care of it for us.

Worth noting, once we have our HTML editor completely done, we'll be working on a Markdown editor and add that as well, but first we need to have our current one solid and stable.

I have no rush on getting this task on, you can leave it open and start stabbing when you have a dedicated time to work and hack it.

**Comment by AmirSavand** [comment]
We'll do https://github.com/quilljs/quill
