### ISSUE TITLE
Auto-Save mode

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#851]
**Is your feature request related to a problem? Please describe.**
If I close my widow or lose internet connection all of my work will be gone.

**Describe the solution you'd like**
Post editor should handle auto saving.
While I write, in the background it should perform auto saving.

If I open a published post and changed something, it should catch the change and save it and keep it as unpublished changes.

If I try to create new entry, right away after any changes it should save them as well.

All the new changes should be saved until I publish them explicitly.

**Additional context**

No additional changes need to be done on the frontend, at least they're very minimal to handle.
When something changes, as usual send the whole data to the backend to the same endpoint, however do not send "status" key when doing auto save in the background. 

When you send new data all the data will be saved as unpublished changes and after success request, backend will return a new field called `entrydraft` . if that comes back, it means the entry has unpublished changes and you should let user know there are changes that need to be published (you change the publish button to say "Publish Changes").

When wanting to publish the changes, explicitly send the `status` as published.

**Comment by Alir3z4** [comment]
@AmirSavand now the backend has been deployed to production, this is really important to work on and get done.

Please consider this with higher priority that other tasks

**Comment by AmirSavand** [comment]
Yes.

**Comment by AmirSavand** [comment]
Should we let user know that the entry is being saved? A tiny _**Saving...**_ will do.

**Comment by Alir3z4** [comment]
Yes and let them know when was the last time saved as well.

**Comment by AmirSavand** [comment]
Alright.

**Comment by Alir3z4** [comment]
@AmirSavand Where are we with this ?

**Comment by AmirSavand** [comment]
No progress at all.

**Comment by AmirSavand** [comment]
Yea, remember our discussion? about all the time I put in and all failed.

Is everything fixed in backend? I can finish this.
