### ISSUE TITLE
Cannot login into dashboard

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#862]
I try to login, it's welcomes me but it doesn't log me in at all.
It even creates the cookies.
Looking at the console of chrome I see the following error:
```
vendor.de121fce.js:1 TypeError: o.user.getSites is not a function
    at scripts.e30b2cf4.js:1
    at r.$broadcast (vendor.de121fce.js:1)
    at scripts.e30b2cf4.js:1
    at x (vendor.de121fce.js:1)
    at vendor.de121fce.js:1
    at vendor.de121fce.js:1
    at r.$digest (vendor.de121fce.js:1)
    at r.$apply (vendor.de121fce.js:1)
    at vendor.de121fce.js:1
    at m (vendor.de121fce.js:1)
    at XMLHttpRequest.h.onload (vendor.de121fce.js:1)
    at XMLHttpRequest.e (vendor.de121fce.js:1) undefined
(anonymous) @ vendor.de121fce.js:1
```

**To Reproduce**
1. Go to https://dash.gonevis.com/#!/login/
2. Fill up the credentials
3. Press login button

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/591113/40514498-fac1df0e-5fb1-11e8-98cc-5abdb79fcc7c.png)

**Desktop:**
 - OS: Windows
 - Browser Chrome
 - Version Version 66.0.3359.181

**Comment by AmirSavand** [comment]
I got the sentry error, this is possibly because of your cookies on draft domain, clear your cache then try agian.

Only happens to us developers since we switch between development, draft, production domains.

**Comment by Alir3z4** [comment]
That's the thing.
I haven't switched to staging at all.

I've been on production only.

**Comment by AmirSavand** [comment]
Since you're the only one with this problem, we should wait to see if we get any sentry errors of this.

If so, this is serious and need to be fixed.

Were you able to login after clearing cookies?

**Comment by Alir3z4** [comment]
Yes, most of the time I do.
Can't we just do this anyway ?

Most of the time I have login again and I'm not logged in.
Not sure why to be honest/

**Comment by AmirSavand** [comment]
That error happens when front-end fails to store cookies (no sites in cookies).

We can prevent this error and telling user that we couldn't store cookies in your browser. But still, this only happens to us.

**Comment by Alir3z4** [comment]
I know it's only "us" but the thing is I'm not that kind of "us" since I
haven't switched to staging for a long long time and this is happening to
me for multiple times recently.
Anyway, why would frontend fails to store cookies ?

Worth noting; I think the JWT was already in the cookies (not sure)

**Comment by AmirSavand** [comment]
As far as I know, when cookie of other domains are stored, you can't store anymore.

**Comment by AmirSavand** [comment]
As you can see: https://sentry.io/savand-bros/gonevis-dash/issues/563743414/ only 1 user and 1 event is stored, this clearly happened once according to sentry.

If this happens again, it'll be top priority.

**Comment by Alir3z4** [comment]
Don't we store on `.gonevis.com` domain ?
What other domain we're talking about and why should they prevent it ?

**Comment by AmirSavand** [comment]
I'm not sure, all I know if cookie fails to store (we call the save function but it just doesn't store when you're logged in staging or dev) that error will happen.

**Comment by Alir3z4** [comment]
Ok, let this issue to be open unless it never happens again (will happen :D)

**Comment by AmirSavand** [comment]
I still can prevent this error by checking if cookies are saved or not but it's a minor issue.

**Comment by Alir3z4** [comment]
Yeah, since it's minor don't mind it, get other stuff fixed please.
