### ISSUE TITLE
Publish "How to Disable Google Analytics on GoNevis.com"

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#865]
Continuing #864

**Comment by Alir3z4** [comment]
Who would like to to take care of this ?

**Comment by AmirSavand** [comment]
@ArsalanSavand Finish it.

**Comment by Alir3z4** [comment]
Ok, will do.
Thanks

**Comment by Alir3z4** [comment]
@AmirSavand the image is not really nice.
What's up with the long arrow ?

![image](https://user-images.githubusercontent.com/591113/41860108-6f19c8b4-78a6-11e8-98ee-9cd9eb24fbd7.png)

It could be much smaller and just a tiny row to show the field or just a select box (border) around the field, that would be much better.

I'll publish now, but please re-upload a better one.
