### ISSUE TITLE
Markdown Editor

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#872]
Using Markdown as an option for editor would be something really good.
Many writers would love to work with Markdown due to its simplicity and ease of syntax and being cleaner.

Requirements:

* Inserting image: This should be fairly straight-forward. once image has been selected from the image selector modal, then insert it into the text area with Markdown image syntax.
* Preview pan.

Notes:
* ~~Backend should receive markdown and not rendered html.~~
* ~~backend should keep a flag regarding the editor in use so it knows how to render them. for instance `syntax='html'` or `syntax='md'`~~

**Comment by Alir3z4** [comment]
SimpleMDE is a nice package to work with https://github.com/sparksuite/simplemde-markdown-editor. However it doesn't have a built-in or complete angular support.
I was able to find these resources that can help us develop it:

* https://github.com/sparksuite/simplemde-markdown-editor/issues/367
* https://github.com/hansottowirtz/simplemde-angular

**Comment by Alir3z4** [comment]
Last time I discussed with @ArsalanSavand and we had a good talk about using the current editor to support Markdown, which is really good.

if we can do that, it would be great.
Because I really don't want to repeat all the tiny features in both HTML and Markdown editor, it's so annoying to keep them in sync.

One solution to rule them all please <3

**Comment by ArsalanSavand** [comment]
@Alir3z4 Should our markdown editor be a completely another module? or a module that supports our current editor?

Both solutions are fine by me.

**Comment by AmirSavand** [comment]
I want markdown too!

**Comment by AmirSavand** [comment]
Changing editor should be available in one of these:

- Editor page
- Blog settings
- Account settings

**Comment by LarsFosdal** [comment]
Markdown is very useful. Quicker than a mouse driven GUI.  Regarding the comments of wanting to avoid dual editors, and to lessen the complexity, I tend to believe that it would be option 2 mentioned by @Alir3z4 that is the preferable method. Reverting HTML to markdown seems a near impossible task - considering nested tags and more complex wrappers - unless you do extensive use of div styles?

**Comment by ukanf** [comment]
Any updates on this topic?
