### ISSUE TITLE
Background is scrolled down when scrolling down the page

### ISSUE THREAD

**Issue by Momjo** [SavandBros/gonevis-dash#875]
**Not scrolled:**

![screen shot 2018-06-06 at 09 09 29](https://user-images.githubusercontent.com/19407713/41022632-7834464a-696a-11e8-851a-9dec4f838460.png)

**Scrolled** down:

![screen shot 2018-06-06 at 09 12 30](https://user-images.githubusercontent.com/19407713/41022640-7c4c14ce-696a-11e8-8fcb-4421e1074a33.png)

**Comment by AmirSavand** [comment]
It's easy, search for css background types.

**Comment by Momjo** [comment]
i will do it

**Comment by AmirSavand** [comment]
Your cover is thin I guess.

**Comment by Alir3z4** [comment]
> Your cover is thin I guess.

Should this be considered a bug ?
What can we do to fix this ?

**Comment by AmirSavand** [comment]
@Alir3z4 the covers in this theme should be full screen images.

**Comment by AmirSavand** [comment]
@Momjo Provide the link of this post so I can check it.

**Comment by Momjo** [comment]
@AmirSavand  this bug is on every background in FALL theme

Here is the Post link : 

https://mojo.gonevis.com/just-do-your-job/

**Comment by Momjo** [comment]
I tested it in SAFARI browser, it works fine.
I think it's only in chrome or just in my chrome

**Comment by AmirSavand** [comment]
![image](https://user-images.githubusercontent.com/4629328/41289413-b531dff4-6e5a-11e8-8505-9b5c55879e80.png)

![image](https://user-images.githubusercontent.com/4629328/41289434-c7f03bb8-6e5a-11e8-962e-e8154de81c77.png)

This is Opera browser same as chrome, it works fine.

**Comment by Momjo** [comment]
actually i have the latest version of chrome( 67.0.3396.79 ).
did you try it too in chrome?
