### ISSUE TITLE
Can't upload image to editor in Firefox

### ISSUE THREAD

**Issue by AmirSavand** [SavandBros/gonevis-dash#877]

**Comment by AmirSavand** [comment]
Can not be fixed, only way is to change our editor.

**Comment by AmirSavand** [comment]
#836

**Comment by Alir3z4** [comment]
This should not be closed.
If the error is from our editor.
Then leave it open until editor is changed this issue is fixed as well.

Does it make sense ?

**Comment by AmirSavand** [comment]
But we already have it's task but ok this is fine too.

**Comment by AmirSavand** [comment]
Then this should be fixed #836.

**Comment by Alir3z4** [comment]
Correct, we do have a task for changing the editor but it's a separate task
and doesn't address this issue directly.
Therefore closing this will make "changing the editor" less important.
You may label this as "blocked" until editor is changed.
