### ISSUE TITLE
User account/profile update link is not clear

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#881]
User account view is not clear.
I see many users have signed up and yet they don't have their information updated, like Name, Location, etc.

After getting in touch with some of them, I found out some (_tons_) of them didn't know where is the profile update link in dashboard..

After having a good look at it, I agree with them. The link is well hidden.

What do you propose ?

**Comment by AmirSavand** [comment]
Clicking on Username then View Account...

**Comment by Alir3z4** [comment]
This is a good idea.
In this way we also teach them where things can be found.
I see your pull request and add some requests changes.
Great work ;)
