### ISSUE TITLE
Remove ChartJS

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#884]
We have a very little usage of it
@AmirSavand I never have seen it in action.
We can add another charting library or even a more simpler one later, this one is very big and we have a very little usage of it.

**Comment by AmirSavand** [comment]
Because we don't have statistics.

We'll do.

**Comment by Alir3z4** [comment]
Yeah, we currently don't have.
However bundling something we don't use or barely use is annoying
