### ISSUE TITLE
See followers

### ISSUE THREAD

**Issue by Momjo** [SavandBros/gonevis-dash#886]

**Comment by Alir3z4** [comment]
das ist nett, stimme ich zu.

@Momjo we only know "Lori" language :D

**Comment by Alir3z4** [comment]
@AmirSavand what do you think about this ?
What would be a good design for this to include in dash ?

**Comment by AmirSavand** [comment]
I don't understand this language.

**Comment by Momjo** [comment]
This language is something like "Shoshtari" language.

**Comment by Alir3z4** [comment]
> This language is something like "Shoshtari" language.

Oh my god! "Shushtari" is what it is :D



> I don't understand this language.

He's asking to see the followers of his blog

**Comment by AmirSavand** [comment]
@Alir3z4 does backend provide that information?

**Comment by Alir3z4** [comment]
Not yet.
How do you think we should show that?
Also, what information do you need exactly?

**Comment by AmirSavand** [comment]
List of user objects...

**Comment by Alir3z4** [comment]
I know list of user objects :D
I meant what data of users, so I can pass you exact data and not a bloated
json with tons of info that you may not need.

**Comment by AmirSavand** [comment]
Username, picture, url.

**Comment by Alir3z4** [comment]
OK.
Also, please revert the issue title to german one.
The whole fun was that <3

I'll start marking that endpoint now

**Comment by AmirSavand** [comment]
Negative, we might search for issues later and this won't come up.

**Comment by Alir3z4** [comment]
> Negative, we might search for issues later and this won't come up if it was non English.

Issue comments also show up in the search result, but I get your point.
Anyway, the endpoint is available on the staging and you can start working on it.
The endpoint: `/api/zero/website/site/<SITE_ID>/subscribers/`, it supports pagination as well.

**Comment by AmirSavand** [comment]
@ArsalanSavand from main view or blog settings view, user should be able to see followers in a modal.
