### ISSUE TITLE
Using Webpack merge feature

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#891]
In order to have a cleaner webpack.config.js file.

**Comment by Alir3z4** [comment]
@AmirSavand actually you can take care of this already.
You've done something similar to other project of yours.

It's assigned to you now.

**Comment by ArsalanSavand** [comment]
See this link, https://webpack.js.org/guides/production/

**Comment by Alir3z4** [comment]
> @Alir3z4 how many environments do we have beside "staging", "development", "production" ?

Nothing more than that, that's all we have.



> See this link, https://webpack.js.org/guides/production/

We already take care of the production part properly at:

https://github.com/SavandBros/gonevis-dash/blob/master/webpack.config.js#L201-L263

**Comment by AmirSavand** [comment]
What about the test stuff, this seems too complex.

**Comment by Alir3z4** [comment]
I'll take care of it today.
No worries.

**Comment by Alir3z4** [comment]
Just spent some time on this.
I don't think this is something valuable.

It adds more complexity to our configuration.
The current webpack config is easier to manager to be honest.
