### ISSUE TITLE
Deprecation warning when running tests

### ISSUE THREAD

**Issue by AmirSavand** [SavandBros/gonevis-dash#899]
Run `npm test` and see this warning:

```
DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
```

**Comment by Alir3z4** [comment]
This is just a warning and can be ignored.
It started when I upgraded to webpack v4.
There are some good results on it https://duckduckgo.com/?q=DeprecationWarning%3A+Tapable.plugin+is+deprecated.+Use+new+API+on+%60.hooks%60+instead&ia=web

**Comment by Alir3z4** [comment]
This is not something we can do, it's about upstream to fix it.
I guess in future versions of webpack it will go away.

If it becomes a problem, feel free to reopen.
