### ISSUE TITLE
Handle permission (role) on frontend

### ISSUE THREAD

**Issue by ArsalanSavand** [SavandBros/gonevis-dash#907]
Don't call forbidden requests.

**Comment by Alir3z4** [comment]
When a call to a forbidden request is made the backend returns the appropriate error and http status.
What exactly you'd like to achieve via this ?

**Comment by AmirSavand** [comment]
This is the issue where we request admin data when user has a lower role.

We should check roles before making requests.

**Comment by Alir3z4** [comment]
This should be tightly integrated with the backend.

Could you explain what you have in mind?

**Comment by AmirSavand** [comment]
For example, if user is not owner of the blog, we should not request the API of template config.
