### ISSUE TITLE
Remember what blog I was working on

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#910]
Currently dashboard doesn't remember which blog I was working in, so when I enter the dashboard it select one for me (_the latest ?_).

When opening the dashboard, I want to work on the same blog that I closed the dash, Either login or openning it after a while.

**Comment by AmirSavand** [comment]
Last blog can be stored in browser, nice feature.

**Comment by AmirSavand** [comment]
@ArsalanSavand use `localStorageService` and in `AppRun` where the `s` param is set to 0 by default, set  it to `lastBlog` if exists.

**Comment by Alir3z4** [comment]
> Last blog can be stored in browser, nice feature.

I don't think that would be enough.
We need that to be saved in the backend as well.
to have it available on different browsers, mobile as well after logout
