### ISSUE TITLE
Enhancing Auto Save posts

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#911]
2 things to work on:

* Auto Save when creating new posts https://github.com/SavandBros/gonevis-dash/pull/904#issuecomment-401002509
* Using the combination of time interval and changes for auto saving: If after N seconds, there no changes then API should not be called. Just keep a flag when data changes or the old data and new data have differences and use that flag/boolean when N seconds interval passes.

**Comment by AmirSavand** [comment]
Since we have the same controller for new and edit, I think we can change url without reloading view.
