### ISSUE TITLE
Using SCSS instead of direct CSS

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#916]
What do you think of working with SCSS instead of current way of doing directly via CSS?

I see our CSS files are getting big and bigger every day.
Using SCSS will make the code much easier to follow.

To get started, I found 2 tools that get the current CSS files into SCSS.

* https://css2sass.herokuapp.com/
* https://www.css2scss.com/

I liked the https://www.css2scss.com/ more since it uses variables as well, however it will mess up the comments as well since it don't know how to preserve them.

Let me know what do you think ?

**Comment by AmirSavand** [comment]
We can use it and it's good for theming but shouldn't the conversion be handled by webpack?

**Comment by Alir3z4** [comment]
No, you got it wrong!
The tools I mentioned can help you to convert the existing CSS files to
SCSS and from there you can continue writing SCSS.
Then you can always write SCSS and webpack will take care if conversion.

Makes sense ?

**Comment by Alir3z4** [comment]
Do you think it would be good to write SCSS instead of CSS ?
webpack can pick them up and convert to CSS for the final build

**Comment by AmirSavand** [comment]
We can benefit. We'll keep it open for later. Not a major requirement.
