### ISSUE TITLE
Let the editor to fly with more features 

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#941]
I don't want to make the editor bloated but we're using a tiny fraction of the features from the editor.
Let the toolbar to be feature rich.

![image](https://user-images.githubusercontent.com/591113/42823493-581661a8-89e6-11e8-8121-f2a09e736788.png)

Almost all of the above are relevant when writing content, let them be enabled, except the font selector..

Also add a tiny button to show advanced features of the editor, like expanding them etc...
All the highlighted buttons below should be hidden by default and shows when clicking "advanced" or "more" button on the editor,

![image](https://user-images.githubusercontent.com/591113/42823807-221d5f7e-89e7-11e8-8893-dda8f33e4d3f.png)

**Comment by AmirSavand** [comment]
I think this is too old and we've got lots of more features.
