### ISSUE TITLE
SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by AmirSavand** [SavandBros/gonevis-dash#946]
https://sentry.io/savand-bros/gonevis-dash/issues/611452725/

```
SyntaxError: Unexpected token '<'
  at None (/main.64da5edb306793c9aa0d.js:1)
```

**Comment by Alir3z4** [comment]
How bad is this error though ?

**Comment by AmirSavand** [comment]
I don't think this error is valid, if we had syntax error, we couldn't even build.

Also there are no source maps. We can't diagnose it.

**Comment by AmirSavand** [comment]
All we can do is set source maps and wait for it to happen again.

**Comment by Alir3z4** [comment]
Isn't reported by sentry?

**Comment by AmirSavand** [comment]
Yes but we can't see the source, it's in main.js which is minified.

**Comment by Alir3z4** [comment]
hmm, that's annoying. We already have the sourcemaps available.
Sentry should have picked it up.
How old is this bug, recent ?

**Comment by Alir3z4** [comment]
I mean like after we switched to webpack build ?

**Comment by AmirSavand** [comment]
I guess yea and it's recent yea.

**Comment by AmirSavand** [comment]
We'll investigate it but it's impossible that we have syntax error.

**Comment by Alir3z4** [comment]
Interesting.
