### ISSUE TITLE
Fix the tour system

### ISSUE THREAD

**Issue by AmirSavand** [SavandBros/gonevis-dash#949]
We can use modal, slides or both.

**Comment by Alir3z4** [comment]
@AmirSavand ping!

**Comment by AmirSavand** [comment]
It needs some work, it can wait for rewrite but I think it should be fixed right now since most of the work is done, there are some tiny bugs that comes with the bootstrap popover, we may end up using modal which fits for mobile (small screen) too.

**Comment by AmirSavand** [comment]
Won't fix it, will remove it and rewrite a new tour sytem: https://github.com/SavandBros/gonevis-dash/issues/1179
