### ISSUE TITLE
Post Preview windows make navigation link to be like mobile

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#965]
Have a look at the navigation links in the navbar of the page shown in the preview modal:

![image](https://user-images.githubusercontent.com/591113/43861119-8daf89c8-9b5e-11e8-8a1e-5dcac688dbd2.png)

This is the desktop mode and I think the navbar should not be compacted.
The navbar would be OK like this in the desktop mode:

![image](https://user-images.githubusercontent.com/591113/43861194-bf4010c0-9b5e-11e8-8c79-64942ded21e4.png)

What do you think @AmirSavand  ?

**Comment by AmirSavand** [comment]
When there are more navs, they run into eachother and mess up.
Amir Savand,
https://amir.savandbros.com

**Comment by AmirSavand** [comment]
I think the modal should be wider.
Amir Savand,
https://amir.savandbros.com

**Comment by Alir3z4** [comment]
I agree. It should be wide, but how wide ?
Even if we make it wide, wouldn't the navs be compacted when the user screens is small ? would that happen though ?

**Comment by Alir3z4** [comment]
@AmirSavand ping, we need to have a resolution on this to close it.

**Comment by AmirSavand** [comment]
Currently, themes collapse the navbar for tablet or smaller devices. Only thing that makes sense is making the preview navbar full width.
