### ISSUE TITLE
Remove Entry.lead attribute usage

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/gonevis-dash#973]
It has been removed from the backend.
It only adds more confusion to the code and I think the excerpt can take its role.

**Comment by AmirSavand** [comment]
Is excerpt generated automatically if there's none?

**Comment by Alir3z4** [comment]
> Is excerpt generated automatically if there's none?

@AmirSavand it will be yes.

Please take care of this as soon a possible, because currently it's blocking the backend deployment.
