### ISSUE TITLE
Remove color property from navigation?

### ISSUE THREAD

**Issue by ArsalanSavand** [SavandBros/gonevis-dash#985]
I think it's a option that is not needed.
And for sure we have to use a module for color picker, for what? For a option that has no need.

What do you think ? @Alir3z4 & @AmirSavand .

**Comment by Alir3z4** [comment]
I don't think we need color, maybe for extreme customization request, but right now I don't see any usage of it.

It actually makes the UX more complicated and confusing and I never been in a position to use it as well.
@AmirSavand what do you think ?

**Comment by AmirSavand** [comment]
@Alir3z4 I use it to color my external links:

![image](https://user-images.githubusercontent.com/4629328/46917463-9be28780-cfd8-11e8-9a30-3d6e49fd977a.png)

I don't see why we should remove a feature we got.

**Comment by ArsalanSavand** [comment]
@Alir3z4 & @AmirSavand , I think we should remove this feature on frontend for now.
@AmirSavand are you suggesting we should keep this feature only for templates that have dark navbars? I don't think we should keep this complicated feature only for a few themes.

@Alir3z4 what is your final decision?

**Comment by AmirSavand** [comment]
No has nothing to do with dark theme!

I wanna change color of my navs to anything I want, period.

**Comment by AmirSavand** [comment]
@Alir3z4 reopen if you disagree.

**Comment by Alir3z4** [comment]
You dictator!
Make the UX much better @AmirSavand then 
The current UX is not friendly, make the UX to educate the user how to use it and how to take the most out if it.

**Comment by Alir3z4** [comment]
To be honest it is a feature and I like to keep it, but as long as it's not a double edge sword!
We should not make a new feature that causes more confusion or push user to go an extra kilometer (_mile in US :D_).

@AmirSavand wipe out your memory and go on this page like a normal user and see how it seems to be useless.

* What a color means ?
* What it does ? 
* Why it it there ? 
* Why should I use it ? 
* What's the benefit ? 
* etc.

Those are the question that comes to the user's mind and mine too
What's your plan to improve and simplify it ?

**Comment by Alir3z4** [comment]
My vote to not remove but enhance it properly.
Let me know what do you think @AmirSavand .

**Comment by Alir3z4** [comment]
It's a UX matter, would be great to come up with a better idea.
Or just remove it.

**Comment by ArsalanSavand** [comment]
@AmirSavand Any last ideas?

My true answer is to remove it if we don't have a good UX for it. Since having color for your navigations is not a common thing, I say remove it.

**Comment by AmirSavand** [comment]
Popover.

**Comment by AmirSavand** [comment]
Closing since you've failed to convince us why we should remove this.

But better UX to represent the color property of a navigation would be good.
